# Generated by Django 5.0.1 on 2024-04-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0027_customer_customer_pimage_seller_seller_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_status',
            field=models.CharField(default='Approved', max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='s_status',
            field=models.CharField(default='Approved', max_length=30),
        ),
    ]
