# Generated by Django 5.0.1 on 2024-04-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0028_alter_customer_c_status_alter_seller_s_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='is_active',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
